// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Aeropuertos
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Nombre { get; set; } = null!;

    [StringLength(15)]
    public string Abreviatura { get; set; } = null!;

    [StringLength(6)]
    public string CiudadId { get; set; } = null!;

    [ForeignKey("CiudadId")]
    [InverseProperty("Aeropuertos")]
    public virtual Ciudades Ciudad { get; set; } = null!;

    [InverseProperty("Aeropuerto")]
    public virtual ICollection<RiesgosDatosAeronave> RiesgosDatosAeronave { get; set; } = new List<RiesgosDatosAeronave>();
}