// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Asegurados
{
    [Key]
    [StringLength(10)]
    public string Id { get; set; } = null!;

    [StringLength(50)]
    public string Nombre { get; set; } = null!;

    [StringLength(15)]
    public string Abreviatura { get; set; } = null!;

    [StringLength(15)]
    public string? AseguradoId { get; set; }

    [InverseProperty("AseguradoNavigation")]
    public virtual ICollection<Riesgos> Riesgos { get; set; } = new List<Riesgos>();
}