// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class BienesAsegurados
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Nombre { get; set; } = null!;

    [StringLength(10)]
    public string? RamoId { get; set; }

    public bool? Generico { get; set; }

    [ForeignKey("RamoId")]
    [InverseProperty("BienesAsegurados")]
    public virtual Ramos? Ramo { get; set; }
}