// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Ciudades
{
    [Key]
    [StringLength(6)]
    public string Id { get; set; } = null!;

    [StringLength(25)]
    public string Nombre { get; set; } = null!;

    [StringLength(6)]
    public string Abreviatura { get; set; } = null!;

    [StringLength(6)]
    public string PaisId { get; set; } = null!;

    [InverseProperty("Ciudad")]
    public virtual ICollection<Aeropuertos> Aeropuertos { get; set; } = new List<Aeropuertos>();

    [ForeignKey("PaisId")]
    [InverseProperty("Ciudades")]
    public virtual Paises Pais { get; set; } = null!;
}