// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Coberturas
{
    [Key]
    [StringLength(10)]
    public string Id { get; set; } = null!;

    [StringLength(50)]
    public string Descripcion { get; set; } = null!;

    [StringLength(15)]
    public string Abreviatura { get; set; } = null!;

    [StringLength(10)]
    public string? RamoId { get; set; }

    [InverseProperty("Cobertura")]
    public virtual ICollection<PlanesCobertura_Coberturas> PlanesCobertura_Coberturas { get; set; } = new List<PlanesCobertura_Coberturas>();

    [ForeignKey("RamoId")]
    [InverseProperty("Coberturas")]
    public virtual Ramos? Ramo { get; set; }

    [InverseProperty("Cobertura")]
    public virtual ICollection<RiesgosCoberturas> RiesgosCoberturas { get; set; } = new List<RiesgosCoberturas>();

    [InverseProperty("Cobertura")]
    public virtual ICollection<SiniestrosCoberturas> SiniestrosCoberturas { get; set; } = new List<SiniestrosCoberturas>();

    [InverseProperty("Cobertura")]
    public virtual ICollection<SiniestrosMovimientos> SiniestrosMovimientos { get; set; } = new List<SiniestrosMovimientos>();
}