// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Companias
{
    [Key]
    [StringLength(10)]
    public string Id { get; set; } = null!;

    [StringLength(50)]
    public string Nombre { get; set; } = null!;

    [StringLength(15)]
    public string Abreviatura { get; set; } = null!;

    [StringLength(15)]
    public string? CompaniaId { get; set; }

    public bool Nosotros { get; set; }

    [StringLength(75)]
    public string? Direccion1 { get; set; }

    [StringLength(75)]
    public string? Direccion2 { get; set; }

    [StringLength(75)]
    public string? Direccion3 { get; set; }

    [StringLength(10)]
    public string? Tipo { get; set; }

    [InverseProperty("CompaniaNavigation")]
    public virtual ICollection<Cuotas> Cuotas { get; set; } = new List<Cuotas>();

    [InverseProperty("Compania")]
    public virtual ICollection<Documentos> Documentos { get; set; } = new List<Documentos>();

    [InverseProperty("CompaniaNosotrosNavigation")]
    public virtual ICollection<Empresa> Empresa { get; set; } = new List<Empresa>();

    [InverseProperty("Compania")]
    public virtual ICollection<Remesas> Remesas { get; set; } = new List<Remesas>();

    [InverseProperty("CedenteNavigation")]
    public virtual ICollection<Riesgos> RiesgosCedenteNavigation { get; set; } = new List<Riesgos>();

    [InverseProperty("Compania")]
    public virtual ICollection<RiesgosCompanias> RiesgosCompanias { get; set; } = new List<RiesgosCompanias>();

    [InverseProperty("CorredorNavigation")]
    public virtual ICollection<Riesgos> RiesgosCorredorNavigation { get; set; } = new List<Riesgos>();

    [InverseProperty("Compania")]
    public virtual ICollection<RiesgosProrrata> RiesgosProrrata { get; set; } = new List<RiesgosProrrata>();

    [InverseProperty("Ajustador")]
    public virtual ICollection<Siniestros> Siniestros { get; set; } = new List<Siniestros>();
}