// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Cuotas
{
    [Key]
    public int Id { get; set; }

    public int Source_EntityId { get; set; }

    public int? Source_SubEntityId { get; set; }

    [StringLength(10)]
    public string Source_Origen { get; set; } = null!;

    [StringLength(25)]
    public string Source_Numero { get; set; } = null!;

    [StringLength(10)]
    public string Compania { get; set; } = null!;

    [StringLength(10)]
    public string Moneda { get; set; } = null!;

    public short Numero { get; set; }

    public short Cantidad { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaEmision { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Fecha { get; set; }

    public short DiasVencimiento { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime FechaVencimiento { get; set; }

    [Column(TypeName = "money")]
    public decimal MontoOriginal { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal Factor { get; set; }

    [Column(TypeName = "money")]
    public decimal Monto { get; set; }

    [StringLength(10)]
    public string Cia { get; set; } = null!;

    [ForeignKey("Cia")]
    [InverseProperty("Cuotas")]
    public virtual Empresa CiaNavigation { get; set; } = null!;

    [ForeignKey("Compania")]
    [InverseProperty("Cuotas")]
    public virtual Companias CompaniaNavigation { get; set; } = null!;

    [ForeignKey("Moneda")]
    [InverseProperty("Cuotas")]
    public virtual Monedas MonedaNavigation { get; set; } = null!;

    [InverseProperty("Cuota")]
    public virtual ICollection<Pagos> Pagos { get; set; } = new List<Pagos>();

    [ForeignKey("Source_EntityId")]
    [InverseProperty("Cuotas")]
    public virtual Riesgos Source_Entity { get; set; } = null!;
}