// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

[Index("EntidadId", "Origen", Name = "IX_Documentos")]
public partial class Documentos
{
    [Key]
    public int Id { get; set; }

    [StringLength(10)]
    public string Origen { get; set; } = null!;

    public int EntidadId { get; set; }

    [StringLength(10)]
    public string CompaniaId { get; set; } = null!;

    public DateOnly Fecha { get; set; }

    [StringLength(10)]
    public string Tipo { get; set; } = null!;

    [StringLength(25)]
    public string Numero { get; set; } = null!;

    [ForeignKey("CompaniaId")]
    [InverseProperty("Documentos")]
    public virtual Companias Compania { get; set; } = null!;
}