// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Empresa
{
    [Key]
    [StringLength(10)]
    public string Id { get; set; } = null!;

    [StringLength(70)]
    public string Nombre { get; set; } = null!;

    [StringLength(15)]
    public string Abreviatura { get; set; } = null!;

    [StringLength(10)]
    public string? CompaniaNosotros { get; set; }

    [StringLength(50)]
    public string? Direccion1 { get; set; }

    [StringLength(50)]
    public string? Direccion2 { get; set; }

    [StringLength(50)]
    public string? Direccion3 { get; set; }

    [StringLength(50)]
    public string? Direccion4 { get; set; }

    [StringLength(50)]
    public string? Direccion5 { get; set; }

    [StringLength(50)]
    public string? Email { get; set; }

    [StringLength(25)]
    public string? Telefono1 { get; set; }

    [StringLength(25)]
    public string? Telefono2 { get; set; }

    [ForeignKey("CompaniaNosotros")]
    [InverseProperty("Empresa")]
    public virtual Companias? CompaniaNosotrosNavigation { get; set; }

    [InverseProperty("CiaNavigation")]
    public virtual ICollection<Cuotas> Cuotas { get; set; } = new List<Cuotas>();

    [InverseProperty("CiaNavigation")]
    public virtual ICollection<Remesas> Remesas { get; set; } = new List<Remesas>();

    [InverseProperty("CiaNavigation")]
    public virtual ICollection<Riesgos> Riesgos { get; set; } = new List<Riesgos>();
}