// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Marcas
{
    [Key]
    [StringLength(10)]
    public string Id { get; set; } = null!;

    [StringLength(25)]
    public string Descripcion { get; set; } = null!;

    [StringLength(15)]
    public string Abreviatura { get; set; } = null!;

    [InverseProperty("MakeNavigation")]
    public virtual ICollection<RiesgosDatosAeronave> RiesgosDatosAeronave { get; set; } = new List<RiesgosDatosAeronave>();
}