// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Monedas
{
    [Key]
    [StringLength(10)]
    public string Id { get; set; } = null!;

    [StringLength(20)]
    public string Descripcion { get; set; } = null!;

    [StringLength(10)]
    public string Simbolo { get; set; } = null!;

    public bool? Defecto { get; set; }

    [InverseProperty("MonedaNavigation")]
    public virtual ICollection<Cuotas> Cuotas { get; set; } = new List<Cuotas>();

    [InverseProperty("Moneda")]
    public virtual ICollection<Pagos> Pagos { get; set; } = new List<Pagos>();

    [InverseProperty("Moneda")]
    public virtual ICollection<PlanesCobertura> PlanesCobertura { get; set; } = new List<PlanesCobertura>();

    [InverseProperty("Moneda")]
    public virtual ICollection<PlanesCobertura_Coberturas> PlanesCobertura_Coberturas { get; set; } = new List<PlanesCobertura_Coberturas>();

    [InverseProperty("Moneda")]
    public virtual ICollection<Remesas> Remesas { get; set; } = new List<Remesas>();

    [InverseProperty("MonedaNavigation")]
    public virtual ICollection<Riesgos> Riesgos { get; set; } = new List<Riesgos>();

    [InverseProperty("Moneda")]
    public virtual ICollection<RiesgosCoberturas> RiesgosCoberturas { get; set; } = new List<RiesgosCoberturas>();

    [InverseProperty("Moneda")]
    public virtual ICollection<RiesgosCompanias> RiesgosCompanias { get; set; } = new List<RiesgosCompanias>();

    [InverseProperty("Moneda")]
    public virtual ICollection<RiesgosProrrata> RiesgosProrrata { get; set; } = new List<RiesgosProrrata>();

    [InverseProperty("Moneda")]
    public virtual ICollection<SiniestrosCoberturas> SiniestrosCoberturas { get; set; } = new List<SiniestrosCoberturas>();

    [InverseProperty("Moneda")]
    public virtual ICollection<SiniestrosMovimientos> SiniestrosMovimientos { get; set; } = new List<SiniestrosMovimientos>();
}