// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Pagos
{
    [Key]
    public int Id { get; set; }

    public int RemesaId { get; set; }

    public int CuotaId { get; set; }

    [StringLength(10)]
    public string MonedaId { get; set; } = null!;

    public DateOnly Fecha { get; set; }

    public bool Completo { get; set; }

    [Column(TypeName = "money")]
    public decimal Monto { get; set; }

    [ForeignKey("CuotaId")]
    [InverseProperty("Pagos")]
    public virtual Cuotas Cuota { get; set; } = null!;

    [ForeignKey("MonedaId")]
    [InverseProperty("Pagos")]
    public virtual Monedas Moneda { get; set; } = null!;

    [ForeignKey("RemesaId")]
    [InverseProperty("Pagos")]
    public virtual Remesas Remesa { get; set; } = null!;
}