// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Paises
{
    [Key]
    [StringLength(6)]
    public string Id { get; set; } = null!;

    [StringLength(25)]
    public string Nombre { get; set; } = null!;

    [StringLength(6)]
    public string Abreviatura { get; set; } = null!;

    public bool? Defecto { get; set; }

    [InverseProperty("Pais")]
    public virtual ICollection<Ciudades> Ciudades { get; set; } = new List<Ciudades>();

    [InverseProperty("PaisNavigation")]
    public virtual ICollection<Riesgos> Riesgos { get; set; } = new List<Riesgos>();

    [InverseProperty("Country")]
    public virtual ICollection<RiesgosDatosAeronave> RiesgosDatosAeronave { get; set; } = new List<RiesgosDatosAeronave>();
}