// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class PlanesCobertura
{
    [Key]
    public int Id { get; set; }

    [StringLength(50)]
    public string Nombre { get; set; } = null!;

    [StringLength(10)]
    public string MonedaId { get; set; } = null!;

    [StringLength(10)]
    public string? RamoId { get; set; }

    [ForeignKey("MonedaId")]
    [InverseProperty("PlanesCobertura")]
    public virtual Monedas Moneda { get; set; } = null!;

    [InverseProperty("Plan")]
    public virtual ICollection<PlanesCobertura_Coberturas> PlanesCobertura_Coberturas { get; set; } = new List<PlanesCobertura_Coberturas>();

    [ForeignKey("RamoId")]
    [InverseProperty("PlanesCobertura")]
    public virtual Ramos? Ramo { get; set; }
}