// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class PlanesCobertura_Coberturas
{
    [Key]
    public int Id { get; set; }

    public int PlanId { get; set; }

    [StringLength(10)]
    public string? MonedaId { get; set; }

    [StringLength(10)]
    public string CoberturaId { get; set; } = null!;

    [Column(TypeName = "money")]
    public decimal? SumaAsegurada { get; set; }

    [Column(TypeName = "decimal(10, 6)")]
    public decimal? Tasa { get; set; }

    [Column(TypeName = "money")]
    public decimal? Prima { get; set; }

    [ForeignKey("CoberturaId")]
    [InverseProperty("PlanesCobertura_Coberturas")]
    public virtual Coberturas Cobertura { get; set; } = null!;

    [ForeignKey("MonedaId")]
    [InverseProperty("PlanesCobertura_Coberturas")]
    public virtual Monedas? Moneda { get; set; }

    [ForeignKey("PlanId")]
    [InverseProperty("PlanesCobertura_Coberturas")]
    public virtual PlanesCobertura Plan { get; set; } = null!;
}