// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class ProcesosUsuarios
{
    [Key]
    public int Id { get; set; }

    [Column(TypeName = "smalldatetime")]
    public DateTime Fecha { get; set; }

    [StringLength(30)]
    public string Categoria { get; set; } = null!;

    [StringLength(30)]
    public string SubCategoria { get; set; } = null!;

    [StringLength(300)]
    public string Descripcion { get; set; } = null!;

    [StringLength(25)]
    public string Usuario { get; set; } = null!;

    [StringLength(100)]
    public string? SubTituloReport { get; set; }

    [InverseProperty("Proceso")]
    public virtual ICollection<Tmp_CuotasCobradasYPagadas_ConsultaCobranzas_Report> Tmp_CuotasCobradasYPagadas_ConsultaCobranzas_Report { get; set; } = new List<Tmp_CuotasCobradasYPagadas_ConsultaCobranzas_Report>();

    [InverseProperty("Proceso")]
    public virtual ICollection<Tmp_Generales_ConsultaEmision_Report> Tmp_Generales_ConsultaEmision_Report { get; set; } = new List<Tmp_Generales_ConsultaEmision_Report>();
}