// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Ramos
{
    [Key]
    [StringLength(10)]
    public string Id { get; set; } = null!;

    [StringLength(50)]
    public string Descripcion { get; set; } = null!;

    [StringLength(15)]
    public string Abreviatura { get; set; } = null!;

    [StringLength(5)]
    public string? PrefijoNumeroRiesgo { get; set; }

    public bool? Defecto { get; set; }

    [InverseProperty("Ramo")]
    public virtual ICollection<BienesAsegurados> BienesAsegurados { get; set; } = new List<BienesAsegurados>();

    [InverseProperty("Ramo")]
    public virtual ICollection<Coberturas> Coberturas { get; set; } = new List<Coberturas>();

    [InverseProperty("Ramo")]
    public virtual ICollection<PlanesCobertura> PlanesCobertura { get; set; } = new List<PlanesCobertura>();

    [InverseProperty("RamoNavigation")]
    public virtual ICollection<Riesgos> Riesgos { get; set; } = new List<Riesgos>();
}