// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Remesas
{
    [Key]
    public int Id { get; set; }

    public DateOnly Fecha { get; set; }

    [StringLength(10)]
    public string CompaniaId { get; set; } = null!;

    [StringLength(10)]
    public string MonedaId { get; set; } = null!;

    [StringLength(2)]
    public string MiSu { get; set; } = null!;

    [Column(TypeName = "decimal(10, 6)")]
    public decimal Tasa { get; set; }

    public DateOnly? FCerrada { get; set; }

    [StringLength(500)]
    public string Observaciones { get; set; } = null!;

    [StringLength(25)]
    public string InstPago_Numero { get; set; } = null!;

    [StringLength(6)]
    public string InstPago_Tipo { get; set; } = null!;

    [StringLength(10)]
    public string InstPago_Banco { get; set; } = null!;

    [Column(TypeName = "money")]
    public decimal InstPago_Monto { get; set; }

    [StringLength(10)]
    public string Cia { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime FRegistro { get; set; }

    [StringLength(25)]
    public string Usuario { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? FUltAct { get; set; }

    [StringLength(25)]
    public string? UltUsuario { get; set; }

    [ForeignKey("Cia")]
    [InverseProperty("Remesas")]
    public virtual Empresa CiaNavigation { get; set; } = null!;

    [ForeignKey("CompaniaId")]
    [InverseProperty("Remesas")]
    public virtual Companias Compania { get; set; } = null!;

    [ForeignKey("InstPago_Banco")]
    [InverseProperty("Remesas")]
    public virtual Bancos InstPago_BancoNavigation { get; set; } = null!;

    [ForeignKey("MonedaId")]
    [InverseProperty("Remesas")]
    public virtual Monedas Moneda { get; set; } = null!;

    [InverseProperty("Remesa")]
    public virtual ICollection<Pagos> Pagos { get; set; } = new List<Pagos>();
}