// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class RiesgosDatosAeronave
{
    [Key]
    public int Id { get; set; }

    public int RiesgoId { get; set; }

    public short Year { get; set; }

    [StringLength(10)]
    public string Make { get; set; } = null!;

    [StringLength(10)]
    public string Model { get; set; } = null!;

    [StringLength(10)]
    public string Wings { get; set; } = null!;

    public short Pax { get; set; }

    public short Crew { get; set; }

    public short Baby { get; set; }

    [StringLength(20)]
    public string Registration { get; set; } = null!;

    [StringLength(25)]
    public string UsedFor { get; set; } = null!;

    [StringLength(6)]
    public string CountryId { get; set; } = null!;

    [StringLength(16)]
    public string? Engine { get; set; }

    [StringLength(16)]
    public string? EngineType { get; set; }

    [StringLength(16)]
    public string? Operation { get; set; }

    [StringLength(20)]
    public string? Serial { get; set; }

    public int? AeropuertoId { get; set; }

    [ForeignKey("AeropuertoId")]
    [InverseProperty("RiesgosDatosAeronave")]
    public virtual Aeropuertos? Aeropuerto { get; set; }

    [ForeignKey("CountryId")]
    [InverseProperty("RiesgosDatosAeronave")]
    public virtual Paises Country { get; set; } = null!;

    [ForeignKey("Make")]
    [InverseProperty("RiesgosDatosAeronave")]
    public virtual Marcas MakeNavigation { get; set; } = null!;

    [ForeignKey("Model")]
    [InverseProperty("RiesgosDatosAeronave")]
    public virtual Modelos ModelNavigation { get; set; } = null!;

    [ForeignKey("RiesgoId")]
    [InverseProperty("RiesgosDatosAeronave")]
    public virtual Riesgos Riesgo { get; set; } = null!;
}