// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class RiesgosCoberturas
{
    [Key]
    public int Id { get; set; }

    public int RiesgoId { get; set; }

    [StringLength(10)]
    public string CoberturaId { get; set; } = null!;

    [StringLength(10)]
    public string MonedaId { get; set; } = null!;

    public short? Cantidad { get; set; }

    [Column(TypeName = "money")]
    public decimal? SumaAseguradaUnidad { get; set; }

    [Column(TypeName = "money")]
    public decimal SumaAsegurada { get; set; }

    [Column(TypeName = "money")]
    public decimal? Limite { get; set; }

    [Column(TypeName = "decimal(10, 6)")]
    public decimal? Tasa { get; set; }

    [Column(TypeName = "money")]
    public decimal Prima { get; set; }

    [ForeignKey("CoberturaId")]
    [InverseProperty("RiesgosCoberturas")]
    public virtual Coberturas Cobertura { get; set; } = null!;

    [ForeignKey("MonedaId")]
    [InverseProperty("RiesgosCoberturas")]
    public virtual Monedas Moneda { get; set; } = null!;

    [ForeignKey("RiesgoId")]
    [InverseProperty("RiesgosCoberturas")]
    public virtual Riesgos Riesgo { get; set; } = null!;
}