// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

[Index("Referencia", "Endoso", Name = "IX_Riesgos", IsUnique = true)]
public partial class Riesgos
{
    [Key]
    public int Id { get; set; }

    public int Numero { get; set; }

    [StringLength(16)]
    public string Referencia { get; set; } = null!;

    public short Endoso { get; set; }

    [StringLength(6)]
    public string TipoEndoso { get; set; } = null!;

    public short AnoSuscripcion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? FechaEmision { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Desde_original { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Hasta_original { get; set; }

    public short? Dias_original { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Desde_aceptacion { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime? Hasta_aceptacion { get; set; }

    public short? Dias_aceptacion { get; set; }

    [StringLength(10)]
    public string Estado { get; set; } = null!;

    [StringLength(10)]
    public string Moneda { get; set; } = null!;

    [StringLength(10)]
    public string Cedente { get; set; } = null!;

    [StringLength(10)]
    public string? Corredor { get; set; }

    [StringLength(10)]
    public string Ramo { get; set; } = null!;

    [StringLength(10)]
    public string Tipo { get; set; } = null!;

    [StringLength(10)]
    public string Asegurado { get; set; } = null!;

    [StringLength(6)]
    public string Pais { get; set; } = null!;

    [StringLength(10)]
    public string Cia { get; set; } = null!;

    [Column(TypeName = "datetime")]
    public DateTime? UploadDate { get; set; }

    public string? Observaciones { get; set; }

    [ForeignKey("Asegurado")]
    [InverseProperty("Riesgos")]
    public virtual Asegurados AseguradoNavigation { get; set; } = null!;

    [ForeignKey("Cedente")]
    [InverseProperty("RiesgosCedenteNavigation")]
    public virtual Companias CedenteNavigation { get; set; } = null!;

    [ForeignKey("Cia")]
    [InverseProperty("Riesgos")]
    public virtual Empresa CiaNavigation { get; set; } = null!;

    [ForeignKey("Corredor")]
    [InverseProperty("RiesgosCorredorNavigation")]
    public virtual Companias? CorredorNavigation { get; set; }

    [InverseProperty("Source_Entity")]
    public virtual ICollection<Cuotas> Cuotas { get; set; } = new List<Cuotas>();

    [ForeignKey("Moneda")]
    [InverseProperty("Riesgos")]
    public virtual Monedas MonedaNavigation { get; set; } = null!;

    [ForeignKey("Pais")]
    [InverseProperty("Riesgos")]
    public virtual Paises PaisNavigation { get; set; } = null!;

    [ForeignKey("Ramo")]
    [InverseProperty("Riesgos")]
    public virtual Ramos RamoNavigation { get; set; } = null!;

    [InverseProperty("Riesgo")]
    public virtual ICollection<RiesgosCoberturas> RiesgosCoberturas { get; set; } = new List<RiesgosCoberturas>();

    [InverseProperty("Riesgo")]
    public virtual ICollection<RiesgosCompanias> RiesgosCompanias { get; set; } = new List<RiesgosCompanias>();

    [InverseProperty("Riesgo")]
    public virtual ICollection<RiesgosDatosAeronave> RiesgosDatosAeronave { get; set; } = new List<RiesgosDatosAeronave>();

    [InverseProperty("Riesgo")]
    public virtual ICollection<RiesgosProrrata> RiesgosProrrata { get; set; } = new List<RiesgosProrrata>();

    [InverseProperty("Riesgo")]
    public virtual ICollection<Siniestros> Siniestros { get; set; } = new List<Siniestros>();

    [ForeignKey("Tipo")]
    [InverseProperty("Riesgos")]
    public virtual Tipos TipoNavigation { get; set; } = null!;
}