// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class RiesgosProrrata
{
    [Key]
    public int Id { get; set; }

    public int RiesgoId { get; set; }

    [StringLength(10)]
    public string CompaniaId { get; set; } = null!;

    public bool Nosotros { get; set; }

    [StringLength(10)]
    public string MonedaId { get; set; } = null!;

    [Column(TypeName = "money")]
    public decimal PrimaAnterior { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal OrdenPorcAnterior { get; set; }

    [Column(TypeName = "money")]
    public decimal PrimaBrutaAnterior { get; set; }

    [Column(TypeName = "money")]
    public decimal Prima { get; set; }

    [Column(TypeName = "decimal(5, 2)")]
    public decimal OrdenPorc { get; set; }

    [Column(TypeName = "money")]
    public decimal PrimaBruta { get; set; }

    [Column(TypeName = "money")]
    public decimal PrimaBrutaDiff { get; set; }

    public short DiasRiesgo { get; set; }

    public short DiasOrden { get; set; }

    [Column(TypeName = "money")]
    public decimal PrimaProrrata { get; set; }

    [ForeignKey("CompaniaId")]
    [InverseProperty("RiesgosProrrata")]
    public virtual Companias Compania { get; set; } = null!;

    [ForeignKey("MonedaId")]
    [InverseProperty("RiesgosProrrata")]
    public virtual Monedas Moneda { get; set; } = null!;

    [ForeignKey("RiesgoId")]
    [InverseProperty("RiesgosProrrata")]
    public virtual Riesgos Riesgo { get; set; } = null!;
}