// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class RiesgosCompanias
{
    [Key]
    public int Id { get; set; }

    public int RiesgoId { get; set; }

    [StringLength(10)]
    public string CompaniaId { get; set; } = null!;

    public bool Nosotros { get; set; }

    [StringLength(10)]
    public string MonedaId { get; set; } = null!;

    [Column(TypeName = "decimal(5, 2)")]
    public decimal OrdenPorc { get; set; }

    [Column(TypeName = "money")]
    public decimal SumaAsegurada { get; set; }

    [Column(TypeName = "money")]
    public decimal SumaReasegurada { get; set; }

    public short Dias { get; set; }

    [Column(TypeName = "money")]
    public decimal Prima { get; set; }

    public short DiasOrden { get; set; }

    [Column(TypeName = "money")]
    public decimal PrimaProrrata { get; set; }

    [Column(TypeName = "money")]
    public decimal PrimaBruta { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal ComPorc { get; set; }

    [Column(TypeName = "money")]
    public decimal Comision { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal ResPorc { get; set; }

    [Column(TypeName = "money")]
    public decimal Reserva { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal CorrPorc { get; set; }

    [Column(TypeName = "money")]
    public decimal Corretaje { get; set; }

    [Column(TypeName = "decimal(9, 6)")]
    public decimal ImpPorc { get; set; }

    [Column(TypeName = "money")]
    public decimal Impuesto { get; set; }

    [Column(TypeName = "money")]
    public decimal PrimaNeta { get; set; }

    [ForeignKey("CompaniaId")]
    [InverseProperty("RiesgosCompanias")]
    public virtual Companias Compania { get; set; } = null!;

    [ForeignKey("MonedaId")]
    [InverseProperty("RiesgosCompanias")]
    public virtual Monedas Moneda { get; set; } = null!;

    [ForeignKey("RiesgoId")]
    [InverseProperty("RiesgosCompanias")]
    public virtual Riesgos Riesgo { get; set; } = null!;
}