// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class SiniestrosMovimientos
{
    [Key]
    public int Id { get; set; }

    public int SiniestroId { get; set; }

    public DateOnly Fecha { get; set; }

    [StringLength(10)]
    public string MonedaId { get; set; } = null!;

    [StringLength(10)]
    public string? CoberturaId { get; set; }

    [StringLength(10)]
    public string Tipo { get; set; } = null!;

    [Column(TypeName = "money")]
    public decimal Monto { get; set; }

    [ForeignKey("CoberturaId")]
    [InverseProperty("SiniestrosMovimientos")]
    public virtual Coberturas? Cobertura { get; set; }

    [ForeignKey("MonedaId")]
    [InverseProperty("SiniestrosMovimientos")]
    public virtual Monedas Moneda { get; set; } = null!;

    [ForeignKey("SiniestroId")]
    [InverseProperty("SiniestrosMovimientos")]
    public virtual Siniestros Siniestro { get; set; } = null!;
}