// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Siniestros
{
    [Key]
    public int Id { get; set; }

    public int RiesgoId { get; set; }

    public int Numero { get; set; }

    public short AnoSuscripcion { get; set; }

    [StringLength(16)]
    public string Referencia { get; set; } = null!;

    public DateOnly FEmision { get; set; }

    public DateOnly FNotificacion { get; set; }

    public DateOnly FOcurrencia { get; set; }

    [StringLength(20)]
    public string Status { get; set; } = null!;

    [StringLength(10)]
    public string? AjustadorId { get; set; }

    [StringLength(50)]
    public string Causa { get; set; } = null!;

    [ForeignKey("AjustadorId")]
    [InverseProperty("Siniestros")]
    public virtual Companias? Ajustador { get; set; }

    [ForeignKey("RiesgoId")]
    [InverseProperty("Siniestros")]
    public virtual Riesgos Riesgo { get; set; } = null!;

    [InverseProperty("Siniestro")]
    public virtual ICollection<SiniestrosCoberturas> SiniestrosCoberturas { get; set; } = new List<SiniestrosCoberturas>();

    [InverseProperty("Siniestro")]
    public virtual ICollection<SiniestrosMovimientos> SiniestrosMovimientos { get; set; } = new List<SiniestrosMovimientos>();
}