// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Tipos
{
    [Key]
    [StringLength(10)]
    public string Id { get; set; } = null!;

    [StringLength(50)]
    public string Descripcion { get; set; } = null!;

    [StringLength(15)]
    public string Abreviatura { get; set; } = null!;

    [StringLength(10)]
    public string Tipo { get; set; } = null!;

    [Unicode(false)]
    public string? Texto { get; set; }

    [Unicode(false)]
    public string? TextoEnglish { get; set; }

    public bool? Defecto { get; set; }

    [InverseProperty("TipoNavigation")]
    public virtual ICollection<Riesgos> Riesgos { get; set; } = new List<Riesgos>();
}