// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Tmp_CuotasCobradasYPagadas_ConsultaCobranzas_Report
{
    [Key]
    public int Id { get; set; }

    public int ProcesoId { get; set; }

    [StringLength(10)]
    public string MonedaId { get; set; } = null!;

    [StringLength(10)]
    public string CompaniaId { get; set; } = null!;

    public int Numero { get; set; }

    public short Endoso { get; set; }

    [StringLength(16)]
    public string Referencia { get; set; } = null!;

    [StringLength(10)]
    public string Origen { get; set; } = null!;

    public short NumeroCuota { get; set; }

    public short CantidadCuotas { get; set; }

    public DateOnly Fecha { get; set; }

    public DateOnly FechaVencimiento { get; set; }

    [Column(TypeName = "money")]
    public decimal Monto { get; set; }

    public int Pago_Remesa { get; set; }

    [StringLength(10)]
    public string Pago_MonedaId { get; set; } = null!;

    public DateOnly Pago_Fecha { get; set; }

    [Column(TypeName = "money")]
    public decimal Pago_Monto { get; set; }

    public bool Pago_Completo { get; set; }

    [StringLength(10)]
    public string Cia { get; set; } = null!;

    [ForeignKey("ProcesoId")]
    [InverseProperty("Tmp_CuotasCobradasYPagadas_ConsultaCobranzas_Report")]
    public virtual ProcesosUsuarios Proceso { get; set; } = null!;
}