// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable enable
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Microsoft.EntityFrameworkCore;

namespace scrweb_blazor.Models.EF_Core;

public partial class Tmp_Generales_ConsultaEmision_Report
{
    [Key]
    public int Id { get; set; }

    public int ProcesoId { get; set; }

    public int RiesgoId { get; set; }

    [StringLength(10)]
    public string MonedaId { get; set; } = null!;

    [StringLength(10)]
    public string RamoId { get; set; } = null!;

    [StringLength(16)]
    public string Numero { get; set; } = null!;

    public short Endoso { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Desde { get; set; }

    [Column(TypeName = "datetime")]
    public DateTime Hasta { get; set; }

    [StringLength(10)]
    public string Estado { get; set; } = null!;

    [StringLength(10)]
    public string CedenteId { get; set; } = null!;

    [StringLength(10)]
    public string Parte { get; set; } = null!;

    [StringLength(10)]
    public string CompaniaId { get; set; } = null!;

    [StringLength(10)]
    public string AseguradoId { get; set; } = null!;

    [Column(TypeName = "money")]
    public decimal SumaAsegurada { get; set; }

    [Column(TypeName = "money")]
    public decimal Prima { get; set; }

    [Column(TypeName = "decimal(10, 6)")]
    public decimal OrdenPorc { get; set; }

    [Column(TypeName = "money")]
    public decimal SumaReasegurada { get; set; }

    [Column(TypeName = "money")]
    public decimal PrimaBruta { get; set; }

    [Column(TypeName = "money")]
    public decimal Com_Corr_Imp_Res { get; set; }

    [Column(TypeName = "money")]
    public decimal PrimaNeta { get; set; }

    [StringLength(10)]
    public string CiaId { get; set; } = null!;

    [ForeignKey("ProcesoId")]
    [InverseProperty("Tmp_Generales_ConsultaEmision_Report")]
    public virtual ProcesosUsuarios Proceso { get; set; } = null!;
}