/*    
	  Viernes, 26 de Abril de 2.024  -   v0.00.003.sql 
	  
	  Agragamos estas tablas al db: monedas, asegurados, compañías y ramos 
*/


BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Ramos
	(
	Id nvarchar(10) NOT NULL,
	Descripcion nvarchar(50) NOT NULL,
	Abreviatura nvarchar(15) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Ramos ADD CONSTRAINT
	PK_Ramos PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Ramos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Companias
	(
	Id nvarchar(10) NOT NULL,
	Nombre nvarchar(50) NOT NULL,
	Abreviatura nvarchar(15) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Companias ADD CONSTRAINT
	PK_Companias PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Companias SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Asegurados
	(
	Id nvarchar(10) NOT NULL,
	Nombre nvarchar(50) NOT NULL,
	Abreviatura nvarchar(15) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Asegurados ADD CONSTRAINT
	PK_Asegurados PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Asegurados SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Monedas
	(
	Id nvarchar(10) NOT NULL,
	Descripcion nvarchar(20) NOT NULL,
	Simbolo nvarchar(10) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Monedas ADD CONSTRAINT
	PK_Monedas PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Monedas SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


Delete From tVersion
Insert Into tVersion(VersionActual, Fecha) Values('v0.00.003', GetDate()) 
