/*    
	  Martes, 22 de Abril de 2.025 - v0.00.048.sql 
	  
	  Agregamos la tabla Bienes Asegurados 
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Ramos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.BienesAsegurados
	(
	Id int NOT NULL IDENTITY (1, 1),
	Nombre nvarchar(50) NOT NULL,
	RamoId nvarchar(10) NULL,
	Generico bit NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.BienesAsegurados ADD CONSTRAINT
	PK_BienesAsegurados PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.BienesAsegurados ADD CONSTRAINT
	FK_BienesAsegurados_Ramos FOREIGN KEY
	(
	RamoId
	) REFERENCES dbo.Ramos
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.BienesAsegurados SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

Delete From tVersion
Insert Into tVersion(VersionActual, Fecha) Values('v0.00.048', GetDate()) 

