/*    
	  Viernes, 18 de Abril de 2.025 - v0.00.047.sql 
	  
	  Agregamos la tabla Aeropuertos 
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Ciudades SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Aeropuertos
	(
	Id int NOT NULL IDENTITY (1, 1),
	Nombre nvarchar(50) NOT NULL,
	Abreviatura nvarchar(15) NOT NULL,
	CiudadId nvarchar(6) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Aeropuertos ADD CONSTRAINT
	PK_Aeropuertos PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Aeropuertos ADD CONSTRAINT
	FK_Aeropuertos_Ciudades FOREIGN KEY
	(
	CiudadId
	) REFERENCES dbo.Ciudades
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Aeropuertos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

Delete From tVersion
Insert Into tVersion(VersionActual, Fecha) Values('v0.00.047', GetDate()) 

