/*    
	  Jueves, 20 de Junio de 2.024  -   v0.00.0012.sql 
	  
	  Agregamos la tabla Cuotas
*/

BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Monedas SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Empresa SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Companias SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
ALTER TABLE dbo.Riesgos SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Cuotas
	(
	Id int NOT NULL IDENTITY (1, 1),
	Source_EntityId int NOT NULL,
	Source_SubEntityId int NULL,
	Source_Origen nvarchar(10) NOT NULL,
	Source_Numero nvarchar(25) NOT NULL,
	Compania nvarchar(10) NOT NULL,
	Moneda nvarchar(10) NOT NULL,
	Numero smallint NOT NULL,
	Cantidad smallint NOT NULL,
	FechaEmision datetime NOT NULL,
	Fecha datetime NOT NULL,
	DiasVencimiento smallint NOT NULL,
	FechaVencimiento datetime NOT NULL,
	MontoOriginal money NOT NULL,
	Factor decimal(9, 6) NOT NULL,
	Monto money NOT NULL,
	Cia nvarchar(10) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Cuotas ADD CONSTRAINT
	PK_Cuotas PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Cuotas ADD CONSTRAINT
	FK_Cuotas_Riesgos FOREIGN KEY
	(
	Source_EntityId
	) REFERENCES dbo.Riesgos
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  CASCADE 
	
GO
ALTER TABLE dbo.Cuotas ADD CONSTRAINT
	FK_Cuotas_Companias FOREIGN KEY
	(
	Compania
	) REFERENCES dbo.Companias
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Cuotas ADD CONSTRAINT
	FK_Cuotas_Monedas FOREIGN KEY
	(
	Moneda
	) REFERENCES dbo.Monedas
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Cuotas ADD CONSTRAINT
	FK_Cuotas_Empresa FOREIGN KEY
	(
	Cia
	) REFERENCES dbo.Empresa
	(
	Id
	) ON UPDATE  NO ACTION 
	 ON DELETE  NO ACTION 
	
GO
ALTER TABLE dbo.Cuotas SET (LOCK_ESCALATION = TABLE)
GO
COMMIT

Delete From tVersion
Insert Into tVersion(VersionActual, Fecha) Values('v0.00.012', GetDate()) 
