/*    
	  Miércoles, 26 de Junio de 2.024  -   v0.00.0016.sql 
	  
	  Agregamos las tablas Suscriptores e Indoles
*/


BEGIN TRANSACTION
SET QUOTED_IDENTIFIER ON
SET ARITHABORT ON
SET NUMERIC_ROUNDABORT OFF
SET CONCAT_NULL_YIELDS_NULL ON
SET ANSI_NULLS ON
SET ANSI_PADDING ON
SET ANSI_WARNINGS ON
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Indoles
	(
	Id nvarchar(10) NOT NULL,
	Descripcion nvarchar(50) NOT NULL,
	Abreviatura nvarchar(15) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Indoles ADD CONSTRAINT
	PK_Indoles PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Indoles SET (LOCK_ESCALATION = TABLE)
GO
COMMIT
BEGIN TRANSACTION
GO
CREATE TABLE dbo.Suscriptores
	(
	Id nvarchar(10) NOT NULL,
	Nombre nvarchar(50) NOT NULL,
	Abreviatura nvarchar(15) NOT NULL
	)  ON [PRIMARY]
GO
ALTER TABLE dbo.Suscriptores ADD CONSTRAINT
	PK_Suscriptores PRIMARY KEY CLUSTERED 
	(
	Id
	) WITH( STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]

GO
ALTER TABLE dbo.Suscriptores SET (LOCK_ESCALATION = TABLE)
GO
COMMIT


Delete From tVersion
Insert Into tVersion(VersionActual, Fecha) Values('v0.00.016', GetDate()) 

